# Auto-generado por giselo-doctor — puedes editar manualmente
# OS: CachyOS Linux (arch)

os:
  platform: linux
  distro: cachyos
  distro_family: arch
  pkg_mgr: paru

output:
  tts_command: ["/usr/bin/piper-tts", "--model", "~/.local/share/piper/es_ES-davefx-medium.onnx", "--output_raw"]

doctor:
  audio_backend: arecord
  notify_backend: notify-send
  hotkey_backend: evdev
  picker_backend: kdialog
  media_backend: playerctl
