#!/usr/bin/env bash
# Giselo installer — Linux (pacman/apt/dnf) + macOS (brew)
# Usage: curl -L https://raw.githubusercontent.com/vanjexdev/crowia/main/install.sh | bash
set -euo pipefail

REPO="https://github.com/vanjexdev/crowia"
INSTALL_DIR="${GISELO_HOME:-$HOME/.local/share/crowia}"
BIN_DIR="$HOME/.local/bin"
LAUNCHER="$BIN_DIR/giselo"

# ── colors ──────────────────────────────────────────────────────────────────
_bold="\033[1m"; _green="\033[0;32m"; _yellow="\033[1;33m"; _red="\033[0;31m"; _nc="\033[0m"
info()  { echo -e "${_green}[giselo]${_nc} $*"; }
warn()  { echo -e "${_yellow}[warn]${_nc}  $*"; }
error() { echo -e "${_red}[error]${_nc} $*" >&2; exit 1; }
step()  { echo -e "\n${_bold}▶ $*${_nc}"; }

# ── OS detection ─────────────────────────────────────────────────────────────
OS="$(uname -s)"
case "$OS" in
  Linux)  PLATFORM="linux" ;;
  Darwin) PLATFORM="mac" ;;
  *)      error "Sistema no soportado: $OS. Instala manualmente." ;;
esac

# ── helpers ──────────────────────────────────────────────────────────────────
has() { command -v "$1" &>/dev/null; }

pkg_install() {
  if   has pacman; then sudo pacman -S --needed --noconfirm "$@"
  elif has apt-get; then sudo apt-get install -y "$@"
  elif has dnf;    then sudo dnf install -y "$@"
  elif has brew;   then brew install "$@"
  else warn "No se encontró gestor de paquetes. Instala manualmente: $*"
  fi
}

# ── system dependencies ───────────────────────────────────────────────────────
step "Verificando dependencias del sistema"

if ! has python3; then
  info "Instalando python3…"
  pkg_install python3
fi

PYVER=$(python3 -c 'import sys; print(sys.version_info[:2] >= (3,10))' 2>/dev/null || echo "False")
[[ "$PYVER" == "True" ]] || error "Se requiere Python 3.10+. Versión actual: $(python3 --version)"
info "Python OK: $(python3 --version)"

if ! has git; then
  info "Instalando git…"
  pkg_install git
fi

# ffmpeg (audio processing)
if ! has ffmpeg; then
  info "Instalando ffmpeg…"
  pkg_install ffmpeg
fi

# piper TTS (Linux only — on Mac user installs manually)
if [[ "$PLATFORM" == "linux" ]] && ! has piper; then
  warn "piper-tts no encontrado. Para voz instala desde: https://github.com/rhasspy/piper/releases"
fi

# evdev (Linux hotkey)
if [[ "$PLATFORM" == "linux" ]]; then
  python3 -c "import evdev" 2>/dev/null || {
    info "Instalando python-evdev…"
    pkg_install python-evdev 2>/dev/null || pip3 install evdev --break-system-packages 2>/dev/null || true
  }
fi

# ── clone / update repo ───────────────────────────────────────────────────────
step "Instalando Giselo en $INSTALL_DIR"

if [[ -d "$INSTALL_DIR/.git" ]]; then
  info "Repositorio existente — actualizando…"
  git -C "$INSTALL_DIR" pull --ff-only
else
  info "Clonando repositorio…"
  git clone "$REPO" "$INSTALL_DIR"
fi

# ── virtual environment ───────────────────────────────────────────────────────
step "Configurando entorno Python"

VENV="$INSTALL_DIR/.venv"
if [[ ! -d "$VENV" ]]; then
  python3 -m venv "$VENV"
fi

"$VENV/bin/pip" install --upgrade pip -q

if [[ -f "$INSTALL_DIR/requirements.txt" ]]; then
  "$VENV/bin/pip" install -r "$INSTALL_DIR/requirements.txt"
  info "Dependencias instaladas desde requirements.txt"
else
  error "requirements.txt no encontrado en $INSTALL_DIR. El repositorio puede estar incompleto."
fi

# ── create launcher ───────────────────────────────────────────────────────────
step "Creando comando 'giselo'"

mkdir -p "$BIN_DIR"

cat > "$LAUNCHER" << 'LAUNCHER_EOF'
#!/usr/bin/env bash
# Giselo launcher — generated by install.sh
GISELO_DIR="${GISELO_HOME:-$HOME/.local/share/crowia}"
VENV="$GISELO_DIR/.venv"

if [[ ! -d "$VENV" ]]; then
  echo "[giselo] Instalación no encontrada en $GISELO_DIR. Ejecuta el instalador de nuevo."
  exit 1
fi

# Sub-commands
CMD="${1:-}"
case "$CMD" in
  web)
    shift
    exec "$VENV/bin/python" "$GISELO_DIR/run_server.py" "$@"
    ;;
  update)
    git -C "$GISELO_DIR" pull --ff-only
    "$VENV/bin/pip" install -r "$GISELO_DIR/requirements.txt" -q 2>/dev/null || true
    echo "[giselo] Actualizado."
    ;;
  *)
    exec "$VENV/bin/python" "$GISELO_DIR/crowia.py" "$@"
    ;;
esac
LAUNCHER_EOF

chmod +x "$LAUNCHER"
info "Launcher creado: $LAUNCHER"

# ── PATH setup ────────────────────────────────────────────────────────────────
step "Configurando PATH"

add_to_path() {
  local file="$1" line="$2"
  if [[ -f "$file" ]] && ! grep -qF "$BIN_DIR" "$file"; then
    echo "$line" >> "$file"
    info "PATH agregado a $file"
  fi
}

export_line='export PATH="$HOME/.local/bin:$PATH"'
fish_line="fish_add_path $HOME/.local/bin"

if [[ "$SHELL" == *fish* ]]; then
  FISH_CFG="$HOME/.config/fish/config.fish"
  add_to_path "$FISH_CFG" "$fish_line"
elif [[ "$SHELL" == *zsh* ]]; then
  add_to_path "$HOME/.zshrc" "$export_line"
else
  add_to_path "$HOME/.bashrc" "$export_line"
fi

# Also add for current session
export PATH="$BIN_DIR:$PATH"

# ── whisper model ─────────────────────────────────────────────────────────────
step "Verificando modelo Whisper"

WHISPER_MODEL_DIR="$HOME/.cache/huggingface/hub"
if [[ ! -d "$WHISPER_MODEL_DIR" ]]; then
  warn "Modelo Whisper no encontrado. Al primer uso se descargará automáticamente (puede tardar)."
fi

# ── done ──────────────────────────────────────────────────────────────────────
echo ""
echo -e "${_green}${_bold}✓ Giselo instalado correctamente${_nc}"
echo ""
echo "  Comandos disponibles:"
echo "    giselo              — lanzar app de escritorio"
echo "    giselo web          — lanzar servidor web"
echo "    giselo --always-on  — modo siempre activo (wake word)"
echo "    giselo update       — actualizar a la última versión"
echo ""
echo "  Config: $HOME/.config/crowia/"
echo "  Logs:   /tmp/crowia/crowia.log"
echo ""

if ! has giselo 2>/dev/null && [[ ":$PATH:" != *":$BIN_DIR:"* ]]; then
  warn "Reinicia tu terminal o ejecuta: source ~/.bashrc (o .zshrc / config.fish)"
fi

# ── Windows note (not supported yet) ─────────────────────────────────────────
# Windows: No soportado oficialmente. Si usas WSL2, ejecuta este script dentro
# del entorno WSL como si fuera Linux. La app de escritorio (PyQt6) requiere
# un servidor X11/Wayland redirigido (ej: WSLg en Windows 11).
